# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: samng.me
email: sam@samng.me
description: >
  There are two ways to live life. One is to live as though nothing is a miracle. <br/>
  The other is to live as though <i>everything</i> is a miracle. - Albert Einstein
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.samng.me" # the base hostname & protocol for your site
twitter_username: samng96
github_username:  samng96
permalink: pretty

# Collections

collections:
  photos:
    output: true

# Build settings
markdown: kramdown
